# Generated by Django 6.0.5 on 2026-06-03 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_lead_is_active_producto_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='producto_interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalog.producto'),
        ),
    ]
