# Generated by Django 6.0.5 on 2026-06-05 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_lead_producto_interes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['marca', 'modelo'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='lead',
            name='desea_comprar',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='aprobado_por_asesor',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('expira_en', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='catalog.lead')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='catalog.producto')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
    ]
