# Generated by Django 6.0.5 on 2026-06-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_lead_cantidad_solicitada'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroAutorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20, unique=True, verbose_name='Número de WhatsApp')),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
